/**
 * Thraxis Arena — where the map's torches are (Cursed Scroll 2, pg. 23).
 *
 * GENERATED by tools/arena/build-thraxis-arena.py. Do not hand-edit: the
 * coordinates here are the ones the map was PAINTED with, and the scene builder
 * puts an AmbientLight on each. Editing one side alone puts lights where there
 * are no torches.
 *
 * Regenerate with:  python3 tools/arena/build-thraxis-arena.py
 */

/** Map size in pixels; square, and a multiple of the grid. */
export const ARENA_SIZE = 2000;

/** Pixels per grid square, and what one square means in feet. */
export const ARENA_GRID = 100;
export const ARENA_FEET_PER_SQUARE = 5;

/** Radius of the granite slab in pixels — the fighting surface. */
export const ARENA_SLAB_RADIUS = 650;

/**
 * Where each torch stands, in map pixels.
 *
 * `x`/`y` is the base, where the stake was driven into the sand — that is what
 * was painted. `flameX`/`flameY` is the fire at the top of the leaning stake,
 * about 3 ft away, and is where the scene's light belongs: a light at the base
 * emits from the wrong end of the torch.
 */
export const ARENA_TORCHES = [
  {
    x: 1712,
    y: 1021,
    flameX: 1727,
    flameY: 963
  },
  {
    x: 1587,
    y: 1427,
    flameX: 1586,
    flameY: 1368
  },
  {
    x: 1357,
    y: 1622,
    flameX: 1369,
    flameY: 1562
  },
  {
    x: 883,
    y: 1725,
    flameX: 900,
    flameY: 1669
  },
  {
    x: 462,
    y: 1452,
    flameX: 466,
    flameY: 1400
  },
  {
    x: 315,
    y: 1271,
    flameX: 330,
    flameY: 1218
  },
  {
    x: 310,
    y: 866,
    flameX: 306,
    flameY: 812
  },
  {
    x: 427,
    y: 514,
    flameX: 445,
    flameY: 448
  },
  {
    x: 959,
    y: 249,
    flameX: 975,
    flameY: 193
  },
  {
    x: 1360,
    y: 368,
    flameX: 1366,
    flameY: 311
  },
  {
    x: 1612,
    y: 651,
    flameX: 1602,
    flameY: 584
  }
];
