/**
 * Shadowdark Enhancer — Loot table linker.
 *
 * Rewrites GM-supplied loot RollTables so each entry becomes a DOCUMENT
 * result linked to its compendium item (existing gear/potions, or the world
 * "Loot" catalog if present); coins stay as text. Operates only on tables
 * already in the world — ships no bundled table content.
 */

import { LootLinker } from "./loot-linker.mjs";
import { isCoinEntry, stripPrice } from "./loot-pack.mjs";
import { findSuitePack } from "../shared/compendium-suite.mjs";
import { isSeaWolfPlunderTable, materializeSeaWolfPlunder } from "./sea-wolf-plunder.mjs";
import { isDeadBanditLootTable, materializeDeadBanditLoot } from "./dead-bandit-loot.mjs";
import { isDiabolicalTreasureTable, materializeDiabolicalTreasure } from "./diabolical-treasure.mjs";

// Pre-migration fallback only — catalog lookups prefer the sde-items suite pack (A-07).
const LOOT_PACK = "world.loot";

/** The current display text of a TableResult (v13 split text → name/description). */
function _resultText(r) {
  // No `.text` fallback: it is a v13 deprecation getter that just aliases
  // name/description, so it can never add anything — only warn.
  return r.name || r.description || "";
}

/** Resolve a loot-entry text to a compendium item uuid (catalog or existing). */
async function _resolveUuid(text, items) {
  const link = LootLinker.findLink(text, items);
  if (link?.uuid) return link.uuid;
  const pack = findSuitePack("sde-items") ?? game.packs.get(LOOT_PACK);
  if (pack) {
    const want = stripPrice(text).toLowerCase();
    const e = [...await pack.getIndex()].find(x => (x.name ?? "").toLowerCase() === want);
    if (e) return e.uuid ?? `Compendium.${pack.collection}.Item.${e._id}`;
  }
  return null;
}

export const LootCatalog = {
  /**
   * Rewrite a loot RollTable's results so each non-coin entry becomes a
   * DOCUMENT result linked to its compendium item (catalog or existing gear);
   * coin entries stay as text. Preserves each result's range + weight. The
   * table then shows real, draggable items and draws them as links.
   * @param {RollTable} table
   * @returns {Promise<{linked,coins,unresolved}>}
   */
  async linkTableItems(table) {
    if (!game.user?.isGM) { ui.notifications?.warn(game.i18n.localize("SDE.loot.catalog.notify.gmOnlyRelink")); return null; }
    // Sea Wolf Plunder is source-qualified and generated by A7.  Route it
    // before the general system-pack-first index: a same-named Item in
    // shadowdark.gear is never an authorized target for this table.
    if (isSeaWolfPlunderTable(table)) return materializeSeaWolfPlunder(table);
    // Dead Bandit rows are feature-bearing source phrases.  Keep them on the
    // exact source-qualified path so generic Bottle/Flask containment cannot
    // claim them.
    if (isDeadBanditLootTable(table)) return materializeDeadBanditLoot(table);
    // Diabolical Treasure has the same source-qualified generated-Item
    // boundary.  Keep it ahead of the general linker so a system-pack Item
    // with the same name can never satisfy a CS1 result.
    if (isDiabolicalTreasureTable(table)) return materializeDiabolicalTreasure(table);
    const items = await LootLinker.buildItemIndex();
    const DOC = CONST.TABLE_RESULT_TYPES.DOCUMENT;
    const summary = { linked: 0, coins: 0, unresolved: 0 };
    // Each row is changed where it stands, and only when something changes:
    // its range, weight, drawn state, image, description and flags stay as the
    // GM left them, and a failed write leaves every row in place. Deleting and
    // recreating every row used to lose all of that, and an empty table was
    // what a failed create left behind.
    const updates = [];

    for (const r of table.results) {
      // Rows already linked to a document are kept — re-resolving by name could
      // drop a good link the item index doesn't cover (e.g. the Shadowdark
      // system's own Treasure 0-3 items).
      if (r.type === DOC) { summary.linked++; continue; }
      const text = _resultText(r);
      const coin = isCoinEntry(text);
      const uuid = coin ? null : await _resolveUuid(text, items);
      if (coin) summary.coins++;
      else if (uuid) summary.linked++;
      else summary.unresolved++;
      // Write the v13 canonical field. documentCollection/documentId are
      // deprecation getters (removed in v15) — see resultUuid() in
      // loot-generator.mjs, and the importer's own create path.
      if (uuid) updates.push({ _id: r.id, type: DOC, documentUuid: uuid });
    }

    if (!updates.length) return { ...summary, unchanged: true };
    await table.updateEmbeddedDocuments("TableResult", updates);
    ui.notifications?.info(game.i18n.format("SDE.loot.catalog.notify.linked", {
      table: table.name, linked: summary.linked, coins: summary.coins, unresolved: summary.unresolved,
    }));
    return summary;
  },

  /**
   * Relink every loot-category RollTable (flag tableType==="loot", or in a
   * "Loot" folder) to its compendium items via linkTableItems.
   */
  async linkLootTables() {
    const tables = game.tables.filter(t =>
      t.getFlag("shadowdark-enhancer", "tableType") === "loot" || t.folder?.name === "Loot"
    );
    const out = [];
    for (const t of tables) out.push({ table: t.name, ...(await this.linkTableItems(t)) });
    return out;
  },
};
